# Generated by Django 6.0.1 on 2026-01-27 03:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('esporte', models.CharField(choices=[('corrida', 'Corrida'), ('yoga', 'Yoga'), ('futebol', 'Futebol'), ('natacao', 'Natação'), ('ciclismo', 'Ciclismo'), ('musculacao', 'Musculação'), ('danca', 'Dança'), ('outro', 'Outro')], max_length=50)),
                ('local', models.CharField(max_length=300)),
                ('dias', models.CharField(help_text='Ex: seg,qua,sex', max_length=100)),
                ('horario', models.TimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='comunidades_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('atividades', models.CharField(blank=True, help_text='Atividades favoritas', max_length=500)),
                ('objetivo', models.CharField(blank=True, help_text='Objetivo fitness', max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
